name: Python Tests

on: 
  push: 
    branches: 
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install django djangorestframework

      - name: Run tests
        run: |
          python manage.py test --verbosity=2 --failfast > results.txt; \
          if [ -f results.txt ]; then echo "Test results:"; cat results.txt; fi
          
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: results.txt
      
      - name: Install SonarScanner
        run: |
          sudo apt-get install -y openjdk-11-jre  # Встановіть Java, якщо потрібно
          wget -qO - https://downloads.sonarsource.com/sonar-scanner/cli/sonar-scanner-cli-4.6.2.2472-linux.zip | funzip > sonar-scanner.zip
          unzip sonar-scanner.zip -d $HOME
          export PATH="$HOME/sonar-scanner-4.6.2.2472-linux/bin:$PATH"

      - name: Run SonarQube analysis
        run: |
          sonar-scanner -Dsonar.projectKey=my_project_key \
                        -Dsonar.host.url=http://localhost:9000 \
                        -Dsonar.login=your_token_here
