name: CI Pipeline

on:
  push:
    branches:
      - master  # Змініть на вашу основну гілку, якщо потрібно
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Встановіть версію Python, яку ви використовуєте

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install django djangorestframework  # Встановіть ваші залежності

      - name: Run tests
        run: |
          python manage.py test --verbosity=2 --failfast > results.txt; \
          if [ -f results.txt ]; then echo "Test results:"; cat results.txt; fi

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: results.txt

  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    needs: test  # Ensure build job runs after the test job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensure full history for SonarQube analysis

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install django djangorestframework

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v3
        env:
          SONAR_TOKEN: a83af31d2553b9e744f8f1e959c0f67f3de9ac43  # Використовуйте GitHub Secrets для збереження токену
        with:
          args: >
            -Dsonar.projectKey=Gerodotry_hoik
            -Dsonar.organization=gero
            -Dsonar.host.url=https://sonarcloud.io
