name: CI Pipeline

on:
  push:
    branches:
      - master  
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install django djangorestframework  

      - name: Run tests
        run: |
          python manage.py test --verbosity=2 --failfast > results.txt; \
          if [ -f results.txt ]; then echo "Test results:"; cat results.txt; fi

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: results.txt

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
        with:
          args: >
            -Dsonar.projectKey=Gerodotry_hoik
            -Dsonar.organization=gero
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.qualitygate.wait=true
  
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    needs: test  # Ensure build job runs after the test job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install django djangorestframework

      - name: Create zip of the project
        run: zip -r project_artifact.zip ./

      - name: Upload project artifact
        uses: actions/upload-artifact@v3
        with:
          name: project-zip-artifact
          path: project_artifact.zip
