name: Python Tests

on: 
  push: 
    branches: 
      - main  # Змініть на вашу основну гілку, якщо потрібно
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'  # Встановіть версію Python, яку ви використовуєте

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install django djangorestframework  # Встановіть ваші залежності

      - name: Run tests
        run: |
          python manage.py test --verbosity=2 --failfast > results.txt; \
          if [ -f results.txt ]; then echo "Test results:"; cat results.txt; fi
          
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: results.txt
      
      - name: Install SonarScanner
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jre unzip  # Встановіть Java та unzip
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
          unzip sonar-scanner-cli-4.6.2.2472-linux.zip -d $HOME
          echo "$HOME/sonar-scanner-4.6.2.2472-linux/bin" >> $GITHUB_PATH  # Додаємо шлях до PATH
      
      - name: Run SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Зберігайте токен у секретах GitHub
        run: |
          sonar-scanner -Dsonar.projectKey=my_django_project_key \
                        -Dsonar.host.url=http://localhost:9000 \
                        -Dsonar.login=${{ secrets.SONAR_TOKEN }}  # Використання токена з секретів
