name: CI Pipeline

on:
  push:
    branches:
      - master  # Змініть на вашу основну гілку, якщо потрібно
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Встановіть версію Python, яку ви використовуєте

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Використовуйте файл залежностей, якщо він є

      - name: Run tests
        run: |
          python manage.py test --verbosity=2 --failfast > results.txt; \
          if [ -f results.txt ]; then echo "Test results:"; cat results.txt; fi

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: results.txt

  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    needs: test  # Build виконується після успішного тестування

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Забезпечує отримання всіх гілок для SonarQube

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Встановіть ту саму версію Python для аналізу

      - name: Install dependencies for build
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Залежності для сканування коду

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v3
        env:
          SONAR_TOKEN: 319a3fc111724bc1bea3b792413169d94d41b606
        with:
          args: >
            -Dsonar.projectKey=gerodotry
            -Dsonar.organization=Gerodotry
            -Dsonar.host.url=https://sonarcloud.io

        

